### ISSUE TITLE
coreVM instructions

### ISSUE THREAD

**Issue by dsnz** [yanzhengli/coreVM#306]
Hello,
Great work !

I searched all repository and could not find a (real) description of instructions/threading/etc for coreVM (plus some helpful examples).
I think I'am not able to locate it. Can you help please ?

**Comment by yanzhengli** [comment]
Hi:

I'm more than glad to give you some pointers. Please bear with me that as this project is still in development, there aren't much documentations available for now. That said, documentation is definitely on the roadmap once the project takes off.

Here are some useful pointers that I hope are helpful to you:

1. You can start with the project by running `make`, which will build the entire project. You will see all the Python tests (run by coreVM) are going to be executed (the fun part).
2. If you are interested in the instruction set of coreVM, you can refer to [src/runtime/instr_fwd.h](https://github.com/yanzhengli/coreVM/blob/dev/src/runtime/instr_fwd.h), which contains description for each instruction.
3. If you want to just play around with individual Python tests, you can just do `make coreVM`, `make artifacts`, and then do `python python/pyta.py python/tests/int.py`. There are dozens of Python tests under `python/tests/`.
4. If you are interested in the Python compiler, which compiles Python source code into coreVM bytecode, you can checkout [python/python_compiler.py](https://github.com/yanzhengli/coreVM/blob/dev/python/python_compiler.py) and [python/code_transformer.py](https://github.com/yanzhengli/coreVM/blob/dev/python/code_transformer.py).
5. If you need more information or have any questions, please feel free to reach out to me.

Thanks.

Best,
Yanzheng Li

**Comment by dsnz** [comment]
In 2. it's all I needed. I just wanted the instruction set to get ideas for a new project of mine (much much simpler than yours).
Thank's a lot and congrats for the work :smile:
